# Generated by Django 4.2 on 2023-04-05 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_description_todo_stat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='stat',
            new_name='description',
        ),
    ]
